Repository CHZZK-Study/HOWMeet-Backend, pull requests merged in 2024-08, with the labels that each got.

#4 [버그 수정] BaseEntity의 disable 컬럼 기본값 설정
  src/main/java/org/chzzk/howmeet/domain/common/entity/BaseEntity.java
Labels: ✔︎pull requests, 🐛bug, 👨🏻‍💻backend, 🗂️db

#5 [기능 추가] Repository 테스트 환경 세팅
  build.gradle
  src/test/java/org/chzzk/howmeet/global/config/RepositoryTest.java
  src/test/java/org/chzzk/howmeet/global/config/TestJpaAuditingConfig.java
  src/test/java/org/chzzk/howmeet/global/config/TestQueryDslConfig.java
  src/test/resources/db/dummy/insert_guest.sql
  src/test/resources/db/dummy/insert_member.sql
  src/test/resources/db/init/init_guest.sql
  src/test/resources/db/init/init_member.sql
Labels: ⚙️chore, ✔︎pull requests, ✨feature, 👨🏻‍💻backend, 🗂️db

#1 [기능 추가] 1회용 회원 기능
  .gitignore
  build.gradle
  src/main/java/org/chzzk/howmeet/domain/common/auth/annotation/Authenticated.java
  src/main/java/org/chzzk/howmeet/domain/common/auth/entity/UserDetails.java
  src/main/java/org/chzzk/howmeet/domain/common/auth/model/AuthPrincipal.java
  src/main/java/org/chzzk/howmeet/domain/common/auth/model/Role.java
  src/main/java/org/chzzk/howmeet/domain/common/entity/BaseEntity.java
  src/main/java/org/chzzk/howmeet/domain/common/model/EncodedPassword.java
  src/main/java/org/chzzk/howmeet/domain/common/model/Nickname.java
  src/main/java/org/chzzk/howmeet/domain/common/model/Password.java
  src/main/java/org/chzzk/howmeet/domain/common/model/converter/EncodedPasswordConverter.java
  src/main/java/org/chzzk/howmeet/domain/common/model/converter/PasswordConverter.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/entity/Member.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/repository/MemberRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/entity/MemberScheduleRecord.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/annotation/TemporaryUser.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/controller/GuestController.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/dto/login/request/GuestLoginRequest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/dto/login/response/GuestLoginResponse.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/dto/signup/request/GuestSignupRequest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/dto/signup/response/GuestSignupResponse.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/entity/Guest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/exception/GuestErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/exception/GuestException.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/repository/GuestQueryDSL.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/repository/GuestQueryDSLImpl.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/repository/GuestRepository.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/service/PasswordValidator.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/util/BCryptPasswordEncoder.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/util/PasswordEncoder.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/entity/Guest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/entity/GuestScheduleRecord.java
  src/main/java/org/chzzk/howmeet/global/config/SecurityConfig.java
  src/main/java/org/chzzk/howmeet/global/config/WebConfig.java
  src/main/java/org/chzzk/howmeet/global/interceptor/AuthenticationInterceptor.java
  src/main/java/org/chzzk/howmeet/global/interceptor/GuestAuthorityInterceptor.java
  src/main/java/org/chzzk/howmeet/global/resolver/AuthPrincipalResolver.java
  src/main/java/org/chzzk/howmeet/global/util/TokenProvider.java
  src/main/resources/application.yml
  src/test/java/org/chzzk/howmeet/common/util/DisplayFormat.java
  src/test/java/org/chzzk/howmeet/domain/common/model/NicknameTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/repository/GuestRepositoryTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/PasswordValidatorTest.java
  src/test/java/org/chzzk/howmeet/fixture/GuestFixture.java
  src/test/resources/db/dummy/insert_guest.sql
  src/test/resources/db/init/init_guest.sql
  src/test/resources/db/init/init_member.sql
Labels: ⚙️chore, ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#10 [기능 추가] 비회원 기능 예외 처리
  build.gradle
  src/main/java/org/chzzk/howmeet/domain/common/auth/exception/AuthErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/common/auth/exception/AuthException.java
  src/main/java/org/chzzk/howmeet/domain/common/auth/model/BadWordFilteringSingleton.java
  src/main/java/org/chzzk/howmeet/domain/common/exception/NicknameErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/common/exception/NicknameException.java
  src/main/java/org/chzzk/howmeet/domain/common/model/Nickname.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/exception/GuestErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestService.java
  src/main/java/org/chzzk/howmeet/global/interceptor/AuthenticationInterceptor.java
  src/main/java/org/chzzk/howmeet/global/interceptor/GuestAuthorityInterceptor.java
  src/test/java/org/chzzk/howmeet/common/util/DisplayFormat.java
  src/test/java/org/chzzk/howmeet/domain/common/model/NicknameTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestServiceTest.java
Labels: ⚙️chore, ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#12 [세팅] restdocs-swagger 세팅
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/test/java/org/chzzk/howmeet/RestDocsTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestServiceTest.java
Labels: ⚙️chore, ✔︎pull requests, 👨🏻‍💻backend, 📃docs

#13 [기능 추가] 방/일정 기능 예외 처리
  build.gradle
  src/main/java/org/chzzk/howmeet/domain/regular/room/exception/RoomErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/exception/RoomException.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/exception/RoomMemberErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/exception/RoomMemberException.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomMemberService.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomService.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/dto/MSRequest.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/dto/MSResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/exception/MSErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/exception/MSException.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/service/MSService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/dto/GSResponse.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/exception/GSErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/exception/GSException.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/service/GSService.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/service/RoomMemberServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/service/RoomServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/schedule/service/MSServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/schedule/service/GSServiceTest.java
  src/test/java/org/chzzk/howmeet/fixture/GSFixture.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend, 🪄refactor

#14 [기능 추가] 회원 기능 예외 처리
  build.gradle
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthService.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/OAuthErrorResponseFactory.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/UnsupportedProviderException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/OAuthProfileException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/OAuthProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/GoogleProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/KakaoProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/NaverProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/OAuthTokenIssueException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/OAuthTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/GoogleTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/KakaoTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/NaverTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/repository/InMemoryOAuthProviderRepository.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthClient.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthTimeoutDecorator.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/ProfileFailHandler.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/TokenIssueFailHandler.java
  src/main/resources/application.yml
Labels: ⚙️chore, ✔︎pull requests, ✨feature, 👨🏻‍💻backend, 🪄refactor

#19 [문서 추가] 방/일정 api 문서 작업
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/org/chzzk/howmeet/TestController.java
  src/main/java/org/chzzk/howmeet/domain/common/embedded/date/impl/ScheduleTime.java
  src/main/java/org/chzzk/howmeet/domain/common/model/ScheduleName.java
  src/main/java/org/chzzk/howmeet/domain/common/util/InviteUrlProvider.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthService.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/model/RoomDescription.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/model/RoomName.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/OAuthErrorResponseFactory.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/UnsupportedProviderException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/OAuthProfileException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/OAuthProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/GoogleProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/KakaoProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/NaverProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/OAuthTokenIssueException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/OAuthTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/GoogleTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/KakaoTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/NaverTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/repository/InMemoryOAuthProviderRepository.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthClient.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthTimeoutDecorator.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/ProfileFailHandler.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/TokenIssueFailHandler.java
  src/main/resources/application.yml
  src/test/java/org/chzzk/howmeet/domain/regular/room/controller/RoomControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/service/RoomMemberServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/service/RoomServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/schedule/controller/MSControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/schedule/service/MSServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/schedule/controller/GSControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/schedule/service/GSServiceTest.java
  src/test/java/org/chzzk/howmeet/fixture/GSFixture.java
  src/test/java/org/chzzk/howmeet/fixture/MSFixture.java
  src/test/java/org/chzzk/howmeet/fixture/RoomFixture.java
  src/test/java/org/chzzk/howmeet/fixture/RoomMemberFixture.java
  src/test/java/org/chzzk/howmeet/global/config/ControllerTest.java
Labels: ⚙️chore, 👨🏻‍💻backend, 📃docs

#15 [기능 추가] 간단 회원 정보 조회
  src/main/java/org/chzzk/howmeet/domain/regular/auth/dto/login/response/MemberLoginResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/repository/MemberRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/OAuthResultHandler.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthService.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/controller/MemberController.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/dto/summary/dto/MemberSummaryDto.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/dto/summary/response/MemberSummaryResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/entity/Member.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/exception/MemberErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/exception/MemberException.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/repository/MemberRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/service/MemberService.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/entity/MemberScheduleRecord.java
  src/main/java/org/chzzk/howmeet/global/interceptor/AuthenticationInterceptor.java
  src/main/java/org/chzzk/howmeet/infra/oauth/model/profile/OAuthProfile.java
  src/test/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/member/repository/MemberRepositoryTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/member/service/MemberServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestServiceTest.java
  src/test/java/org/chzzk/howmeet/fixture/MemberFixture.java
  src/test/resources/db/dummy/insert_member.sql
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend, 🪄refactor

#17 [버그 수정] 비회원 가입 검증
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/repository/GSQueryDSL.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/repository/GSQueryDSLImpl.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/repository/GSRepository.java
  src/test/java/org/chzzk/howmeet/domain/temporary/schedule/repository/GSRepositoryTest.java
Labels: ✔︎pull requests, 🐛bug, 👨🏻‍💻backend

#21 [머지 브랜치] develop 브랜치 유실된 내용 복구
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend

#20 [머지 브랜치] develop 브랜치 유실된 내용 복구
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend

#22 [머지 브랜치] develop 브랜치 유실된 내용 복구
  build.gradle
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthService.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/OAuthErrorResponseFactory.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/UnsupportedProviderException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/OAuthProfileException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/OAuthProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/GoogleProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/KakaoProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/NaverProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/OAuthTokenIssueException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/OAuthTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/GoogleTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/KakaoTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/NaverTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/repository/InMemoryOAuthProviderRepository.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthClient.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthTimeoutDecorator.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/ProfileFailHandler.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/TokenIssueFailHandler.java
  src/main/resources/application.yml
Labels: ✔︎pull requests, 👨🏻‍💻backend

#28 [기능 추가] 비회원 기능 예외 처리
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend

#30 [기능 추가] 간단 회원 정보 조회
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend

#29 [기능 추가] 회원 기능 예외 처리
  build.gradle
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthService.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/OAuthErrorResponseFactory.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/UnsupportedProviderException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/OAuthProfileException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/OAuthProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/GoogleProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/KakaoProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/response/detail/NaverProfileErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/OAuthTokenIssueException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/OAuthTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/GoogleTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/KakaoTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/response/detail/NaverTokenIssueErrorResponse.java
  src/main/java/org/chzzk/howmeet/infra/oauth/repository/InMemoryOAuthProviderRepository.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthClient.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthTimeoutDecorator.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/ProfileFailHandler.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/TokenIssueFailHandler.java
  src/main/resources/application.yml
Labels: ✔︎pull requests, 👨🏻‍💻backend

#18 [기능 수정] OAuth 프로필 조회 반환 타입
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/OAuthResultHandler.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthService.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/UnsupportedProviderException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/model/profile/OAuthProfileFactory.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthClient.java
  src/test/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#32 [기능 추가] 전역 예외 처리
  src/main/java/org/chzzk/howmeet/domain/common/error/DomainErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/common/error/DomainException.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/exception/MemberErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/exception/MemberException.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/exception/RoomErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/exception/RoomException.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/exception/RoomMemberErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/exception/RoomMemberException.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/exception/MSErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/exception/MSException.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/exception/GuestErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/exception/GuestException.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/exception/GSErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/exception/GSException.java
  src/main/java/org/chzzk/howmeet/global/error/ErrorResponse.java
  src/main/java/org/chzzk/howmeet/global/error/GlobalExceptionHandler.java
  src/main/java/org/chzzk/howmeet/infra/error/InfraException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/OAuthClientException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/OAuthServerException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/UnsupportedProviderException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/profile/OAuthProfileException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/token/OAuthTokenIssueException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/ProfileFailHandler.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/TokenIssueFailHandler.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend, 🪄refactor

#33 [기능 추가] 회원/비회원 기능 요청 파라미터 검증
  src/main/java/org/chzzk/howmeet/domain/regular/auth/controller/RegularAuthController.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/dto/login/request/MemberLoginRequest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/controller/GuestController.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/dto/login/request/GuestLoginRequest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/dto/signup/request/GuestSignupRequest.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#34 [기능 수정] 인증 인터셉터 SQL문
  src/main/java/org/chzzk/howmeet/domain/regular/member/repository/MemberQueryDSL.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/repository/MemberQueryDSLImpl.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/repository/MemberRepository.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/repository/GuestQueryDSL.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/repository/GuestQueryDSLImpl.java
  src/main/java/org/chzzk/howmeet/global/interceptor/AuthenticationInterceptor.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor
