Repository CHZZK-Study/HOWMeet-Backend, pull requests merged in 2024-09, with the labels that each got.

#37 [HOTFIX] CORS 설정
  src/main/java/org/chzzk/howmeet/global/config/WebConfig.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#31 [기능 추가] 결과 기능
  src/main/java/org/chzzk/howmeet/domain/common/embedded/date/BaseDate.java
  src/main/java/org/chzzk/howmeet/domain/common/model/NicknameProvider.java
  src/main/java/org/chzzk/howmeet/domain/common/model/Nicknames.java
  src/main/java/org/chzzk/howmeet/domain/common/model/ParticipantDetails.java
  src/main/java/org/chzzk/howmeet/domain/common/model/SelectionDetail.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/entity/Member.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/controller/MSRecordController.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/dto/get/MSRecordGetResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/dto/post/MSRecordPostRequest.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/entity/MemberScheduleRecord.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/model/MSRecordNicknames.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/model/MSRecordSelectionDetail.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/repository/MSRecordRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/service/MSRecordService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/entity/Guest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/controller/GSRecordController.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/dto/get/response/GSRecordGetResponse.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/dto/post/request/GSRecordPostRequest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/entity/GuestScheduleRecord.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/model/GSRecordNicknames.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/model/GSRecordSelectionDetail.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/repository/GSRecordRepository.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/repository/TmpGuestRepository.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/service/GSRecordService.java
  src/test/java/org/chzzk/howmeet/domain/regular/record/repository/MSRecordRepositoryTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/record/service/MSRecordServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/repository/GSRecordRepositoryTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/service/GSRecordServiceTest.java
  src/test/java/org/chzzk/howmeet/fixture/GSRecordFixture.java
  src/test/java/org/chzzk/howmeet/global/config/TestConfig.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#39 [기능 수정] 1회용 회원 로그인
  src/main/java/org/chzzk/howmeet/domain/common/exception/NicknameErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/common/exception/NicknameException.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthService.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/controller/MSRecordController.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/controller/GuestController.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/entity/Guest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/exception/GuestErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestFindService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestSaveService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestService.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestFindServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestSaveServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#40 [기능 추가] 회원 인가 코드 API
  src/main/java/org/chzzk/howmeet/domain/regular/auth/controller/RegularAuthController.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/dto/authorize/request/MemberAuthorizeRequest.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/dto/authorize/response/MemberAuthorizeResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/OAuthResultHandler.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthService.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/service/MemberFindService.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/service/MemberSaveService.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/service/MemberService.java
  src/main/java/org/chzzk/howmeet/infra/oauth/model/OAuthProperties.java
  src/main/java/org/chzzk/howmeet/infra/oauth/model/OAuthProvider.java
  src/test/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/member/service/MemberServiceTest.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#41 [기능 추가] 인증/인가 예외 처리
  build.gradle
  src/main/java/org/chzzk/howmeet/domain/common/auth/exception/AuthErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/common/auth/exception/AuthException.java
  src/main/java/org/chzzk/howmeet/domain/common/auth/exception/AuthenticationException.java
  src/main/java/org/chzzk/howmeet/domain/common/auth/exception/AuthorizationException.java
  src/main/java/org/chzzk/howmeet/global/config/WebConfig.java
  src/main/java/org/chzzk/howmeet/global/error/GlobalExceptionHandler.java
  src/main/java/org/chzzk/howmeet/global/interceptor/AuthenticationInterceptor.java
  src/main/java/org/chzzk/howmeet/global/interceptor/GuestAuthorityInterceptor.java
  src/main/java/org/chzzk/howmeet/global/interceptor/MemberAuthorityInterceptor.java
  src/test/java/org/chzzk/howmeet/HowmeetApplicationTests.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#35 [기능 추가] 방/목록 상세 조회
  src/main/java/org/chzzk/howmeet/domain/common/model/ScheduleName.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/dto/nickname/dto/MemberNicknameDto.java
  src/main/java/org/chzzk/howmeet/domain/regular/member/repository/MemberRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/controller/RoomController.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomListResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/repository/RoomMemberRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomService.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/util/RoomListMapper.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/dto/MSResponse.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/controller/RoomControllerTest.java
  src/test/java/org/chzzk/howmeet/fixture/RoomFixture.java
Labels: ✨feature, 👨🏻‍💻backend, 📃docs, 🪄refactor

#42 [리팩토링] 오류 수정
  src/test/java/org/chzzk/howmeet/domain/regular/room/controller/RoomControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/schedule/controller/MSControllerTest.java
  src/test/java/org/chzzk/howmeet/fixture/RoomFixture.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 📃docs, 🪄refactor

#46 [문서 수정] 비회원 일정 및 룸 테스트 코드 + api 문서 수정
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/controller/GSController.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/dto/GSResponse.java
  src/main/resources/static/docs/SAMPLE - 0.0.1.json
  src/test/java/org/chzzk/howmeet/domain/regular/record/service/MSRecordServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/controller/RoomControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/service/GSRecordServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/schedule/controller/GSControllerTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 📃docs, 🪄refactor

#50 [HOTFIX] @RepositoryTest에 Redis 설정 추가
  src/test/java/org/chzzk/howmeet/global/config/RepositoryTest.java
  src/test/java/org/chzzk/howmeet/infra/redis/TestRedisConfig.java
Labels: ✔︎pull requests, 🐛bug, 👨🏻‍💻backend

#51 [기능 수정] Room 필요없는 값 수정 + rds 오류 해결
  src/main/java/org/chzzk/howmeet/domain/regular/room/controller/RoomController.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomRequest.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/entity/Room.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomService.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/entity/MemberSchedule.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/dto/GSResponse.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/entity/GuestSchedule.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/util/ListToJsonConverter.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/controller/RoomControllerTest.java
  src/test/java/org/chzzk/howmeet/fixture/RoomFixture.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#47 [기능 추가] 방에 속한 회원 조회 API
  src/main/java/org/chzzk/howmeet/domain/regular/room/controller/RoomController.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/controller/RoomMemberController.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/get/response/RoomMemberGetResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/repository/RoomMemberRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomMemberService.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomService.java
  src/main/resources/static/docs/SAMPLE - 0.0.1.json
  src/test/java/org/chzzk/howmeet/domain/regular/room/controller/RoomControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/controller/RoomMemberControllerTest.java
  src/test/java/org/chzzk/howmeet/global/config/ControllerTest.java
  src/test/java/org/chzzk/howmeet/global/config/TestJpaAuditingConfig.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend, 📃docs, 🪄refactor

#53 [기능 수정] 인가 코드 API
  src/main/java/org/chzzk/howmeet/domain/regular/auth/dto/authorize/response/MemberAuthorizeResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthService.java
  src/main/java/org/chzzk/howmeet/infra/oauth/config/OAuthConfig.java
  src/main/java/org/chzzk/howmeet/infra/oauth/dto/authorize/request/OAuthAuthorizeRequest.java
  src/main/java/org/chzzk/howmeet/infra/oauth/dto/authorize/response/OAuthAuthorizePayload.java
  src/main/java/org/chzzk/howmeet/infra/oauth/model/OAuthProperties.java
  src/main/java/org/chzzk/howmeet/infra/oauth/model/OAuthProvider.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthClient.java
  src/main/java/org/chzzk/howmeet/infra/oauth/util/MultiValueMapConverter.java
  src/main/java/org/chzzk/howmeet/infra/oauth/util/serilaizer/ListToCommaSeparatedStringSerializer.java
  src/test/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#45 [문서 추가] 결과 기능 api 문서 작업
  src/main/java/org/chzzk/howmeet/domain/common/model/Nicknames.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/dto/get/MSRecordGetResponse.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/dto/get/response/GSRecordGetResponse.java
  src/test/java/org/chzzk/howmeet/domain/regular/record/controller/MSReordControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/record/repository/MSRecordRepositoryTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/record/service/MSRecordServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/controller/GSRecordControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/repository/GSRecordRepositoryTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/service/GSRecordServiceTest.java
  src/test/java/org/chzzk/howmeet/fixture/GSRecordFixture.java
  src/test/java/org/chzzk/howmeet/fixture/MSRecordFixture.java
Labels: 👨🏻‍💻backend, 📃docs, 🪄refactor

#54 [문서 추가] 회원 API 명세서
  .gitignore
  src/test/java/org/chzzk/howmeet/domain/regular/auth/controller/RegularAuthControllerTest.java
  src/test/java/org/chzzk/howmeet/fixture/MemberFixture.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 📃docs

#55 [문서 추가] 1회용 회원 API 명세서
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/controller/GuestControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/GuestServiceTest.java
  src/test/java/org/chzzk/howmeet/fixture/GuestFixture.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 📃docs

#56 [기능 추가] SQL 예외 핸들링
  src/main/java/org/chzzk/howmeet/global/error/GlobalExceptionHandler.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#61 [기능 수정] 인가 코드 API
  src/main/java/org/chzzk/howmeet/infra/oauth/dto/authorize/request/OAuthAuthorizeRequest.java
  src/test/java/org/chzzk/howmeet/domain/regular/auth/controller/RegularAuthControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#57 [기능 수정] 회원 일정 수정
  src/main/java/org/chzzk/howmeet/domain/regular/room/controller/RoomController.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/controller/MSController.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/dto/MSRequest.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/repository/MSRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/service/MSService.java
  src/test/java/org/chzzk/howmeet/domain/regular/schedule/service/MSServiceTest.java
  src/test/java/org/chzzk/howmeet/fixture/MSFixture.java
  src/test/java/org/chzzk/howmeet/fixture/RoomFixture.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 📃docs, 🪄refactor

#63 [기능 수정] 소셜 로그인
  src/main/java/org/chzzk/howmeet/infra/oauth/config/OAuthConfig.java
  src/main/java/org/chzzk/howmeet/infra/oauth/dto/authorize/request/OAuthAuthorizeRequest.java
  src/main/java/org/chzzk/howmeet/infra/oauth/dto/token/request/OAuthTokenRequest.java
  src/main/java/org/chzzk/howmeet/infra/oauth/model/OAuthProperties.java
  src/main/java/org/chzzk/howmeet/infra/oauth/model/OAuthProvider.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/AuthorizeUriProvider.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthClient.java
  src/main/java/org/chzzk/howmeet/infra/oauth/util/MultiValueMapConverter.java
  src/main/java/org/chzzk/howmeet/infra/oauth/util/converter/MultiValueMapConverter.java
  src/main/java/org/chzzk/howmeet/infra/oauth/util/converter/OAuthParamConverter.java
  src/main/java/org/chzzk/howmeet/infra/oauth/util/converter/TransformationStrategy.java
  src/main/java/org/chzzk/howmeet/infra/oauth/util/mapper/OAuthObjectMapperFactory.java
  src/main/java/org/chzzk/howmeet/infra/oauth/util/serilaizer/ListToSpaceSeparatedStringSerializer.java
  src/test/java/org/chzzk/howmeet/domain/regular/auth/controller/RegularAuthControllerTest.java
Labels: ✔︎pull requests, 🐛bug, 👨🏻‍💻backend, 🪄refactor

#66 [기능 수정] 1회용 로그인 패키지 구조
  src/main/java/org/chzzk/howmeet/domain/common/model/EncodedPassword.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/controller/TemporaryAuthController.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/dto/login/response/GuestLoginResponse.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/dto/signup/request/GuestSignupRequest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/dto/signup/response/GuestSignupResponse.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/service/PasswordValidator.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/service/TemporaryAuthService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/entity/Guest.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/exception/GuestErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/exception/GuestException.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/repository/GuestQueryDSL.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/repository/GuestQueryDSLImpl.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/repository/GuestRepository.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/service/GuestFindService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/service/GuestSaveService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/util/BCryptPasswordEncoder.java
  src/main/java/org/chzzk/howmeet/domain/temporary/guest/util/PasswordEncoder.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/entity/GuestScheduleRecord.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/repository/TmpGuestRepository.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/service/GSRecordService.java
  src/main/java/org/chzzk/howmeet/global/interceptor/AuthenticationInterceptor.java
  src/main/java/org/chzzk/howmeet/infra/config/WebClientConfig.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/controller/TemporaryAuthControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/TemporaryAuthServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/guest/repository/GuestRepositoryTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/guest/service/GuestFindServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/guest/service/GuestSaveServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/repository/GSRecordRepositoryTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/service/GSRecordServiceTest.java
  src/test/java/org/chzzk/howmeet/fixture/GSRecordFixture.java
  src/test/java/org/chzzk/howmeet/fixture/GuestFixture.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#67 [기능 추가] 결과 기능 예외처리
  src/main/java/org/chzzk/howmeet/domain/common/model/Nicknames.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/exception/MSRecordErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/exception/MSRecordException.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/service/MSRecordService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/exception/GSRecordErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/exception/GSRecordException.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/service/GSRecordService.java
  src/test/java/org/chzzk/howmeet/domain/regular/record/controller/MSReordControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/record/service/MSRecordServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/controller/GSRecordControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/service/GSRecordServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend

#68 [기능 수정] 리팩토링 및 요구사항 수정
  src/main/java/org/chzzk/howmeet/domain/regular/member/repository/MemberRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/service/MSRecordService.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/controller/RoomController.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/controller/RoomMemberController.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/PageResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomCreateResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomMemberRequest.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomMemberResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomRequest.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/repository/RoomMemberRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/repository/RoomRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomMemberService.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomService.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthClient.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/controller/RoomControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/controller/RoomMemberControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/service/RoomMemberServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/room/service/RoomServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/schedule/controller/MSControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/schedule/service/MSServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/schedule/controller/GSControllerTest.java
  src/test/java/org/chzzk/howmeet/fixture/RoomFixture.java
  src/test/java/org/chzzk/howmeet/fixture/RoomMemberFixture.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend, 📃docs, 🪄refactor

#65 [기능 수정] OAuth 모듈 서비스 레이어 계층화
  src/main/java/org/chzzk/howmeet/domain/common/auth/util/TokenProvider.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/OAuthResultHandler.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthService.java
  src/main/java/org/chzzk/howmeet/domain/regular/auth/util/MemberMapper.java
  src/main/java/org/chzzk/howmeet/domain/temporary/auth/service/TemporaryAuthService.java
  src/main/java/org/chzzk/howmeet/global/interceptor/AuthenticationInterceptor.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/param/OAuthParamErrorCode.java
  src/main/java/org/chzzk/howmeet/infra/oauth/exception/param/OAuthParamException.java
  src/main/java/org/chzzk/howmeet/infra/oauth/model/profile/OAuthProfile.java
  src/main/java/org/chzzk/howmeet/infra/oauth/model/profile/OAuthProfileFactory.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/OAuthClient.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/authorize/AuthorizeUriProvider.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/authorize/OAuthAuthorizeService.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/decorator/OAuthTimeoutDecorator.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/profile/OAuthProfileService.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/profile/ProfileFailHandler.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/token/OAuthTokenService.java
  src/main/java/org/chzzk/howmeet/infra/oauth/service/token/TokenIssueFailHandler.java
  src/test/java/org/chzzk/howmeet/domain/regular/auth/service/RegularAuthServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/auth/service/TemporaryAuthServiceTest.java
  src/test/java/org/chzzk/howmeet/infra/oauth/fixture/OAuthProviderFixture.java
  src/test/java/org/chzzk/howmeet/infra/oauth/service/OAuthClientTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#69 [기능 추가] 알림 및 일정 확정
  build.gradle
  src/main/java/org/chzzk/howmeet/domain/common/model/SelectionDetail.java
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/controller/ConfirmController.java
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/dto/ConfirmScheduleRequest.java
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/dto/ConfirmScheduleResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/dto/SelectTimeCount.java
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/entity/ConfirmSchedule.java
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/repository/ConfirmRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/service/ConfirmService.java
  src/main/java/org/chzzk/howmeet/domain/regular/fcm/controller/FcmController.java
  src/main/java/org/chzzk/howmeet/domain/regular/fcm/dto/FcmTokenRequest.java
  src/main/java/org/chzzk/howmeet/domain/regular/fcm/dto/VapidResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/fcm/entity/FcmToken.java
  src/main/java/org/chzzk/howmeet/domain/regular/fcm/repository/FcmTokenRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/fcm/service/FcmService.java
  src/main/java/org/chzzk/howmeet/domain/regular/notice/entity/Notice.java
  src/main/java/org/chzzk/howmeet/domain/regular/notice/model/NoticeMessageTemplate.java
  src/main/java/org/chzzk/howmeet/domain/regular/notice/repository/NoticeRepository.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/model/MSRecordNicknames.java
  src/main/java/org/chzzk/howmeet/domain/regular/record/service/MSRecordService.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/entity/MemberSchedule.java
  src/main/java/org/chzzk/howmeet/domain/temporary/record/service/GSRecordService.java
  src/main/java/org/chzzk/howmeet/global/config/FirebaseConfig.java
  src/main/resources/application.yml
  src/test/java/org/chzzk/howmeet/domain/regular/confirm/service/ConfirmServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/fcm/service/FcmServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/record/service/MSRecordServiceTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/controller/GSRecordControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/temporary/record/service/GSRecordServiceTest.java
Labels: ⚙️chore, ✨feature, 👨🏻‍💻backend

#74 [기능 수정] 자정 지남 여부 추가
  src/main/java/org/chzzk/howmeet/domain/common/embedded/date/impl/ScheduleTime.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#78 [기능 수정] 회원 일정 조회 출력 변경, 비회원 일정 생성시 응답값 수정
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomCreateResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomService.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/util/RoomListMapper.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/controller/MSController.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/dto/MSResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/service/MSService.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/controller/GSController.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/dto/GSCreateResponse.java
  src/main/java/org/chzzk/howmeet/domain/temporary/schedule/service/GSService.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#84 [기능 수정] 회원 일정 생성시 id값 반환
  src/main/java/org/chzzk/howmeet/domain/regular/room/util/RoomListMapper.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/controller/MSController.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/dto/MSCreateResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/service/MSService.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#86 [기능 수정] 회원 일정 생성시 룸 id값 반환
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/dto/MSCreateResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/schedule/service/MSService.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#88 [기능 수정] 참여한 방의 갯수 응답값 추가
  src/main/java/org/chzzk/howmeet/domain/regular/room/controller/RoomController.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/dto/PageResponse.java
  src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomService.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#72 [기능 추가] 알림/일정 기능 예외처리
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/controller/ConfirmController.java
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/exception/ConfirmErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/exception/ConfirmException.java
  src/main/java/org/chzzk/howmeet/domain/regular/confirm/service/ConfirmService.java
  src/main/java/org/chzzk/howmeet/domain/regular/fcm/controller/FcmController.java
  src/main/java/org/chzzk/howmeet/domain/regular/fcm/entity/FcmToken.java
  src/main/java/org/chzzk/howmeet/domain/regular/fcm/exception/FcmErrorCode.java
  src/main/java/org/chzzk/howmeet/domain/regular/fcm/exception/FcmErrorException.java
Labels: ✨feature, 👨🏻‍💻backend

#90 [기능 수정] 리프레시 토큰 에러 핸들링
  src/main/java/org/chzzk/howmeet/domain/regular/auth/controller/RegularAuthController.java
  src/main/resources/static/docs/SAMPLE - 0.0.1.json
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#91 [문서 추가] FcmControllerTest, ConfirmControllerTest 추가
  src/test/java/org/chzzk/howmeet/domain/regular/confirm/controller/ConfirmControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/fcm/controller/FcmControllerTest.java
  src/test/java/org/chzzk/howmeet/domain/regular/record/controller/MSReordControllerTest.java
  src/test/java/org/chzzk/howmeet/fixture/MSRecordFixture.java
Labels: 👨🏻‍💻backend, 📃docs
